spring.application.name=opportunity-dashboard
spring.datasource.url=jdbc:postgresql://localhost:5432/opportunity_dashboard
spring.datasource.username=emanmohamed
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
